### ISSUE TITLE
Crash Hamiltonian Cycle - generateRanking()

### ISSUE THREAD

**Issue by gabriel-de-abreu** [GAStudyGroup/vrp#6]
RED
Tour: 
21
1
1
2
5
11
6
15
18
22
3
10
8
1
7
14
12
16
4
13
9
20
19
17

Fitness: 29.3061
Distance: 341.226
Charges: 151 157
Subtours: 
| 7 14 12 16 4 13 9 20 19 17 21 | 
| 2 5 11 6 15 18 22 3 10 8 | 

Size:24

BLUE
Tour: 
1
19
4
13
16
5
12
2
11
17
1
8
18
20
9
14
3
21
1
7
10
15
22
6
1

Fitness: 28.7354
Distance: 348.003
Charges: 115 126 67
Subtours: 
| 19 4 13 16 5 12 2 11 17 | 
| 8 18 20 9 14 3 21 | 
| 7 10 15 22 6 | 

Size:25

**Comment by gabriel-de-abreu** [comment]
#0 0x559a2903927b in HamiltonianCycle::generateRanking() (/home/gabriel/Documentos/vrp-gpx/bin/GA+0x2927b)
    #1 0x559a29040639 in HamiltonianCycle::toHamiltonianCycle[abi:cxx11](Tour, Tour) (/home/gabriel/Documentos/vrp-gpx/bin/GA+0x30639)
    #2 0x559a2914c9db in crossover(Tour&, Tour&) (/home/gabriel/Documentos/vrp-gpx/bin/GA+0x13c9db)
    #3 0x559a29150144 in crossoverPopulation(Population&) (/home/gabriel/Documentos/vrp-gpx/bin/GA+0x140144)
    #4 0x559a2915047a in newGeneration(Population&) (/home/gabriel/Documentos/vrp-gpx/bin/GA+0x14047a)
    #5 0x559a290fc6d4 in startGA() (/home/gabriel/Documentos/vrp-gpx/bin/GA+0xec6d4)
    #6 0x559a2901bb05 in main (/home/gabriel/Documentos/vrp-gpx/bin/GA+0xbb05)
    #7 0x7f044c82bf49 in __libc_start_main (/usr/lib/libc.so.6+0x20f49)
    #8 0x559a2901c0c9 in _start (/home/gabriel/Documentos/vrp-gpx/bin/GA+0xc0c9)

**Comment by gabriel-de-abreu** [comment]
-------------------Entrando hamiltonian------------------
RED
Tour: 
15 9 1 3 12 13 16 4 11 1 14 19 18 1 1 2 5 7 22 8 17 1 20 21 10 6 
Subtours: 
| 20 21 10 6 15 9 | 
| 3 12 13 16 4 11 | 
| 14 19 18 | 
| 2 5 7 22 8 17 | 

Size:26

BLUE
Tour: 
7 2 1 4 19 9 11 12 1 15 22 14 3 1 6 8 1 16 5 17 10 1 20 13 18 21 
Subtours: 
| 20 13 18 21 7 2 | 
| 4 19 9 11 12 | 
| 15 22 14 3 | 
| 6 8 | 
| 16 5 17 10 | 

Size:26
